# Generated by Django 2.1.7 on 2019-09-04 04:27

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=10)),
                ('group_name', models.CharField(max_length=120)),
                ('members_name', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('subtitle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=project.models.image_upload_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group_number', '-updated', '-timestamp'],
            },
        ),
    ]
