# Generated by Django 2.1.7 on 2019-09-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190904_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='used_skill',
            field=models.CharField(default='dummy', max_length=254),
            preserve_default=False,
        ),
    ]
