# Generated by Django 2.1.7 on 2019-09-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=254)),
                ('objective', models.TextField()),
                ('description', models.TextField()),
                ('process', models.TextField()),
            ],
        ),
    ]
